# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0003_auto_20170810_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orderrow',
            name='cost',
        ),
    ]
