# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0004_auto_20170810_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrow',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderrow',
            name='status_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderrow',
            name='status_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order time'),
        ),
    ]
