# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0005_auto_20170810_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrow',
            name='status_active',
        ),
        migrations.RemoveField(
            model_name='orderrow',
            name='status_delivered',
        ),
        migrations.RemoveField(
            model_name='orderrow',
            name='status_purchased',
        ),
        migrations.AddField(
            model_name='order',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
