# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0006_auto_20170811_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_delivered',
        ),
    ]
