# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0010_order_orderrow_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderrow_json',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='burgershop.Category'),
        ),
    ]
